services:
  - type: web
    name: chartink-alert-api
    env: java
    plan: free
    buildCommand: "./mvnw clean package -DskipTests"
    startCommand: "java -jar target/recommendation-0.0.1-SNAPSHOT.jar"
    autoDeploy: true

services:
  - type: web
    name: recommendation-backend
    env: java
    rootDir: backend
    buildCommand: mvn clean package -DskipTests
    startCommand: java -jar target/recommendation-0.0.1-SNAPSHOT.jar
    envVars:
      - key: JAVA_VERSION
        value: 11