services:
  - type: web
    name: recommendation-backend
    env: java
    rootDir: backend
    buildCommand: mvn clean package -DskipTests
    startCommand: java -jar target/*.jar
    envVars:
      - key: JAVA_VERSION
        value: 11
      - key: SPRING_FLYWAY_ENABLED
        value: false