// Stock Basket Configuration
// This file contains the list of stocks for each basket
// Update this file monthly when NIFTY50 composition changes

export const STOCK_BASKETS = {
  NIFTY50: [
    'ADANIENT', 'INDUSINDBK', 'BHARTIARTL', 'SBILIFE', 'ADANIPORTS', 
    'SHRIRAMFIN', 'SBIN', 'EICHERMOT', 'HEROMOTOCO', 'NTPC', 
    'ONGC', 'SUNPHARMA', 'COALINDIA', 'MARUTI', 'AXISBANK', 
    'TECHM', 'JSWSTEEL', 'ASIANPAINT', 'GRASIM', 'INFY', 
    'DRREDDY', 'BAJAJFINSV', 'JIOFIN', 'CIPLA', 'TATACONSUM', 
    'ITC', 'TCS', 'BEL', 'LT', 'HDFCLIFE', 
    'TATASTEEL', 'NIFTY', 'ETERNAL', 'BAJFINANCE', 'WIPRO', 
    'TATAMOTORS', 'RELIANCE', 'APOLLOHOSP', 'HINDALCO', 'ULTRACEMCO', 
    'POWERGRID', 'HDFCBANK', 'HINDUNILVR', 'BAJAJ-AUTO', 'KOTAKBANK', 
    'NESTLEIND', 'TRENT', 'TITAN', 'ICICIBANK', 'M&M', 'HCLTECH'
  ],
  
  BANKNIFTY: [
    'PNB', 'BANKBARODA', 'INDUSINDBK', 'SBIN', 'AXISBANK', 
    'BANDHANBNK', 'AUBANK', 'FEDERALBNK', 'IDFCFIRSTB', 'BANKNIFTY', 
    'HDFCBANK', 'KOTAKBANK', 'ICICIBANK'
  ],
  
  NIFTY200: [
    'PNB', 'BANKBARODA', 'INDUSINDBK', 'SBIN', 'AXISBANK', 
    'BANDHANBNK', 'AUBANK', 'FEDERALBNK', 'IDFCFIRSTB', 'BANKNIFTY', 
    'HDFCBANK', 'KOTAKBANK', 'ICICIBANK'
  ],
  
  NIFTY500: [
    'ADANIPOWER', 'ALIVUS', 'ANANTRAJ', 'NETWEB', 'TANLA', 'IPCALAB', 'ATGL', 'IDEA', 'SUMICHEM', 'PCBL', 
    'ASTERDM', 'LALPATHLAB', 'ADANIGREEN', 'ADANIENT', 'DBREALTY', 'ADANIENSOL', 'METROPOLIS', 'GILLETTE', 'VMM', 'REDINGTON', 
    'NSLNISP', 'GMDCLTD', 'CHOLAHLDNG', 'IREDA', 'MINDACORP', 'HYUNDAI', 'SWIGGY', 'SAMMAANCAP', 'BAYERCROP', 'CGCL', 
    'GVT&D', 'GODREJPROP', 'NIACL', 'UNIONBANK', 'CESC', 'HUDCO', 'TARIL', 'USHAMART', 'KIRLOSENG', 'ABFRL', 
    'JSWINFRA', 'PPLPHARMA', 'UCOBANK', 'FLUOROCHEM', 'MOTILALOFS', 'SAIL', 'CONCORDBIO', 'SUZLON', 'JSL', 'CUB', 
    'SAILIFE', 'CANBK', 'INTELLECT', 'SYRMA', 'AFFLE', 'TBOTEK', 'LTFOODS', 'INOXWIND', 'TORNTPHARM', 'IOB', 
    'NLCINDIA', 'MMTC', 'SWSOLAR', 'JINDALSAW', 'ASHOKLEY', 'JYOTICNC', 'POLYCAB', 'AFCONS', 'BIKAJI', 'DIVISLAB', 
    'JSWENERGY', 'CENTRALBK', 'RADICO', 'IDBI', 'JBCHEPHARM', 'KPRMILL', 'BDL', 'PNB', 'M&MFIN', 'BANKBARODA', 
    'RPOWER', 'AAVAS', 'OIL', 'BANKINDIA', 'HAL', 'KEI', 'INDUSINDBK', 'VIJAYA', 'CENTURYPLY', 'VGUARD', 
    'BPCL', 'ITI', 'SYNGENE', 'BHEL', 'ALKEM', 'ACC', 'FACT', 'SWANCORP', 'POLICYBZR', 'HAPPSTMNDS', 
    'BHARTIARTL', 'SBILIFE', 'HINDPETRO', 'ADANIPORTS', 'RENUKA', 'IIFL', 'SHRIRAMFIN', 'J&KBANK', 'DOMS', 'TATATECH', 
    'GODFRYPHLP', 'APTUS', 'LAURUSLABS', 'LODHA', 'PNBHOUSING', 'TITAGARH', 'SBIN', 'DATAPATTNS', 'CAPLIPOINT', 'IKS', 
    'WELCORP', 'IOC', 'NBCC', 'JKCEMENT', 'GODREJAGRO', 'SARDAEN', 'AEGISLOG', 'IFCI', 'MANKIND', 'ZENSARTECH', 
    'HINDCOPPER', 'SKFINDIA', 'NHPC', 'TRIDENT', 'GMRAIRPORT', 'TATAPOWER', 'GRAPHITE', 'CCL', 'WAAREEENER', 'OBEROIRLTY', 
    'INDUSTOWER', 'EICHERMOT', 'HEROMOTOCO', 'RITES', 'ZEEL', 'PIIND', 'ABSLAMC', 'MCX', 'PGEL', 'DEVYANI', 
    'CAMS', 'AARTIIND', 'KIMS', 'NCC', 'BALKRISIND', 'SJVN', 'UNOMINDA', 'HEG', 'NTPC', 'PATANJALI', 
    'GPIL', 'LICI', 'ONGC', 'YESBANK', 'SUNPHARMA', 'KFINTECH', 'LEMONTREE', 'MRF', 'LUPIN', 'TATACHEM', 
    'DEEPAKFERT', 'RRKABEL', 'ACE', 'SCI', 'MFSL', 'GAIL', 'SOLARINDS', 'NAVA', 'NIVABUPA', 'RHIM', 
    'COALINDIA', 'AKUMS', 'FSL', 'FINPIPE', 'DMART', 'BHARATFORG', 'INDIANB', 'AMBER', 'GLAND', 'TRIVENI', 
    'IRFC', 'MARUTI', 'IEX', 'CHOLAFIN', 'PFC', 'MGL', 'AXISBANK', 'RVNL', 'AMBUJACEM', 'SIEMENS', 
    'NTPCGREEN', 'BHARTIHEXA', 'PHOENIXLTD', 'KPIL', 'BIOCON', 'BASF', 'ERIS', 'STARHEALTH', 'TECHM', 'VBL', 
    'WHIRLPOOL', 'JSWHL', 'APLLTD', 'RCF', 'IRCTC', 'MAHSEAMLES', 'JSWSTEEL', 'BLUESTARCO', 'ALKYLAMINE', 'ASIANPAINT', 
    'EMCURE', 'HDFCAMC', 'AADHARHFC', 'JKTYRE', 'INDGN', 'BANDHANBNK', 'MAHABANK', 'MOTHERSON', 'CRAFTSMAN', 'SCHAEFFLER', 
    'UNITDSPR', 'MARICO', 'TATACOMM', 'GRANULES', 'FIRSTCRY', 'ANGELONE', 'GODREJCP', 'NUVAMA', 'BEML', 'RECLTD', 
    'ABB', 'CAMPUS', 'MAZDOCK', 'SRF', 'NATCOPHARM', 'JUBLFOOD', 'VEDL', 'GRASIM', 'INFY', 'MSUMI', 
    'RTNINDIA', 'ALOKINDS', 'PREMIERENE', 'LICHSGFIN', 'RBLBANK', 'OLAELEC', 'DRREDDY', 'BAJAJFINSV', 'GICRE', 'JIOFIN', 
    'SAGILITY', 'AUBANK', 'AJANTPHARM', 'CIPLA', 'CANFINHOME', 'JINDALSTEL', 'ELECON', 'DABUR', 'INDIACEM', 'TRITURBINE', 
    'TTML', 'TATAELXSI', 'PIDILITIND', 'UBL', 'BAJAJHFL', 'SUNDARMFIN', 'IGL', 'MAPMYINDIA', 'HAVELLS', 'TATACONSUM', 
    'ITC', 'GSPL', 'MPHASIS', 'BOSCHLTD', 'TCS', 'BEL', 'FIVESTAR', 'FEDERALBNK', 'NMDC', 'SHREECEM', 
    'LTIM', 'LTF', 'TIMKEN', 'IDFCFIRSTB', 'LT', 'SAREGAMA', 'HDFCLIFE', 'TATASTEEL', 'CHENNPETRO', 'APLAPOLLO', 
    'COCHINSHIP', 'NEWGEN', 'COHANCE', 'POONAWALLA', 'LLOYDSME', 'ETERNAL', 'IRCON', 'SUNTV', 'CDSL', 'HINDZINC', 
    'SBFC', 'BAJFINANCE', 'ICICIPRULI', 'WIPRO', 'ENGINERSIN', 'VOLTAS', 'CASTROLIND', 'PETRONET', 'ASTRAL', 'TVSMOTOR', 
    'NAM-INDIA', 'CUMMINSIND', 'GESHIP', 'NETWORK18', 'BRITANNIA', 'DEEPAKNTR', 'GLAXO', 'SUNDRMFAST', 'TATAMOTORS', 'RELIANCE', 
    'CYIENT', 'KANSAINER', 'APOLLOHOSP', 'HSCL', 'ABCAPITAL', 'GNFC', 'PRESTIGE', 'NAUKRI', 'INDIGO', 'BATAINDIA', 
    'CGPOWER', 'PRAJIND', 'THERMAX', 'RAYMOND', 'DLF', 'BERGEPAINT', 'KALYANKJIL', 'BSE', 'TEJASNET', 'UTIAMC', 
    'JYOTHYLAB', 'CRISIL', 'ANANDRATHI', 'MUTHOOTFIN', 'HOMEFIRST', 'RAMCOCEM', 'SHYAMMETL', 'GODIGIT', 'LATENTVIEW', 'GRSE', 
    'CHAMBLFERT', 'APOLLOTYRE', 'GUJGASLTD', 'KARURVYSYA', 'JPPOWER', 'INDHOTEL', 'DIXON', 'NH', 'AUROPHARMA', 'ABREL', 
    'KEC', 'HINDALCO', 'SCHNEIDER', 'CROMPTON', 'ULTRACEMCO', 'BBTC', 'NYKAA', 'KIRLOSBROS', 'RAILTEL', 'TECHNOE', 
    'MRPL', 'MEDANTA', 'SONACOMS', 'POWERGRID', 'ZYDUSLIFE', 'HONAUT', 'HDFCBANK', 'AWL', 'BLS', 'NATIONALUM', 
    'ICICIGI', 'KAYNES', 'HINDUNILVR', 'ZENTEC', 'PVRINOX', 'APARINDS', 'LTTS', 'GRAVITA', 'ELGIEQUIP', 'PERSISTENT', 
    'GLENMARK', 'ENDURANCE', 'ARE&M', 'UPL', 'IRB', 'BAJAJ-AUTO', 'KOTAKBANK', 'AIIL', 'COLPAL', 'KAJARIACER', 
    'MAXHEALTH', 'DELHIVERY', 'NESTLEIND', 'HONASA', 'PNCINFRA', 'TRENT', 'KPITTECH', 'TITAN', 'BALRAMCHIN', 'CEATLTD', 
    'CONCOR', 'CERA', 'JUBLPHARMA', 'MANYAVAR', 'WOCKPHARMA', 'ICICIBANK', 'M&M', 'JBMA', 'JUSTDIAL', 'CLEAN', 
    'SUPREMEIND', 'JWL', 'OLECTRA', 'FORTIS', 'SAPPHIRE', '3MINDIA', 'GPPL', 'ASTRAZEN', 'ZFCVINDIA', 'DALBHARAT', 
    'TORNTPOWER', 'PAGEIND', 'HFCL', 'FINCABLES', 'COFORGE', 'SONATSOFTW', 'PFIZER', 'KNRCON', 'BRIGADE', 'BLUEDART', 
    'ABBOTINDIA', 'OFSS', 'BSOFT', 'HCLTECH', 'TIINDIA', 'MASTEK', 'RKFORGE', 'CREDITACC', 'POWERINDIA', 'IGIL', 
    'INOXINDIA', 'COROMANDEL', 'WELSPUNLIV', '360ONE', 'BAJAJHLDNG', 'AIAENG', 'MANAPPURAM', 'LINDEINDIA', 'NAVINFLUOR', 'RAINBOW', 
    'SOBHA', 'INDIAMART', 'WESTLIFE', 'VTL', 'TATAINVEST', 'SBICARD', 'ROUTE', 'HBLENGINE', 'CHALET', 'EXIDEIND', 
    'EIDPARRY', 'NEULANDLAB', 'JMFINANCIL', 'EIHOTEL', 'ESCORTS', 'CARBORUNIV', 'ACMESOLAR', 'ATUL', 'ECLERX', 'SIGNATURE', 
    'RAYMONDLSL', 'POLYMED', 'GODREJIND', 'PTCIL', 'EMAMILTD', 'ASAHIINDIA', 'PAYTM', 'DCMSHRIRAM', 'PEL', 'JUBLINGREA'
  ],
  
  MULTICAP: [
    'ADANIPOWER', 'ALIVUS', 'ORCHPHARMA', 'ANANTRAJ', 'NETWEB', 'TANLA', 'IPCALAB', 'ATGL', 'IDEA', 'SUMICHEM', 
    'PCBL', 'CARTRADE', 'ASTERDM', 'PARADEEP', 'LALPATHLAB', 'SUNCLAY', 'SUPRIYA', 'ADANIGREEN', 'ASTRAMICRO', 'ADANIENT', 
    'INOXGREEN', 'ODIGMA', 'KESORAMIND', 'DCAL', 'DBREALTY', 'ADANIENSOL', 'ROSSARI', 'IXIGO', 'SUPRAJIT', 'IKIO', 
    'METROPOLIS', 'BANCOINDIA', 'GILLETTE', 'VMM', 'REDINGTON', 'NESCO', 'NSLNISP', 'INDIAGLYCO', 'GMDCLTD', 'TDPOWERSYS', 
    'CHOLAHLDNG', 'IREDA', 'MINDACORP', 'AARTIPHARM', 'HYUNDAI', 'PGHH', 'DYNAMATECH', 'EDELWEISS', 'SWIGGY', 'EMIL', 
    'ETHOSLTD', 'SAMMAANCAP', 'BAYERCROP', 'SUDARSCHEM', 'GABRIEL', 'CGCL', 'GVT&D', 'GODREJPROP', 'NIACL', 'UNIONBANK', 
    'CESC', 'HUDCO', 'TARIL', 'USHAMART', 'VENUSPIPES', 'FDC', 'KIRLOSENG', 'ABFRL', 'JSWINFRA', 'BORORENEW', 
    'PPLPHARMA', 'NAVNETEDUL', 'TARC', 'UCOBANK', 'FLUOROCHEM', 'MOTILALOFS', 'RAMKY', 'KOLTEPATIL', 'SAIL', 'CONCORDBIO', 
    'SPLPETRO', 'SUZLON', 'JSL', 'WABAG', 'CUB', 'SAILIFE', 'GUFICBIO', 'PRUDENT', 'CANBK', 'INTELLECT', 
    'SYRMA', 'FUSION', 'AFFLE', 'TBOTEK', 'DCXINDIA', 'ACCELYA', 'DATAMATICS', 'AVANTIFEED', 'TIIL', 'LTFOODS', 
    'INOXWIND', 'HARSHA', 'TORNTPHARM', 'THOMASCOOK', 'AARTIDRUGS', 'HLEGLAS', 'IOB', 'GREENPANEL', 'PGHL', 'NLCINDIA', 
    'MMTC', 'SWSOLAR', 'JINDALSAW', 'ASHOKLEY', 'GALAXYSURF', 'JYOTICNC', 'MTARTECH', 'KSL', 'POLYCAB', 'AFCONS', 
    'BIKAJI', 'DIVISLAB', 'GOCOLORS', 'JSWENERGY', 'VEEDOL', 'GOKEX', 'CENTRALBK', 'RADICO', 'IDBI', 'JBCHEPHARM', 
    'KPRMILL', 'BBL', 'BDL', 'SYMPHONY', 'SANSERA', 'PNB', 'SHARDAMOTR', 'AZAD', 'M&MFIN', 'BANKBARODA', 
    'RPOWER', 'AAVAS', 'OIL', 'BANKINDIA', 'HAL', 'KEI', 'INDUSINDBK', 'STARCEMENT', 'VIJAYA', 'CENTURYPLY', 
    'VGUARD', 'BPCL', 'ITI', 'SHOPERSTOP', 'NRBBEARING', 'SYNGENE', 'SANDUMA', 'BHEL', 'ALKEM', 'ACC', 
    'BIRLACORPN', 'FACT', 'SWANCORP', 'POLICYBZR', 'GRWRHITECH', 'HAPPSTMNDS', 'BHARTIARTL', 'SBILIFE', 'HINDPETRO', 'HEIDELBERG', 
    'VINATIORGA', 'SURYAROSNI', 'ADANIPORTS', 'RENUKA', 'PARAS', 'PATELENG', 'VIPIND', 'SEQUENT', 'IIFL', 'SHRIRAMFIN', 
    'J&KBANK', 'DOMS', 'TATATECH', 'DELTACORP', 'GODFRYPHLP', 'APTUS', 'LAURUSLABS', 'MAHLOG', 'LODHA', 'PNBHOUSING', 
    'TITAGARH', 'SBIN', 'DATAPATTNS', 'CAPLIPOINT', 'IKS', 'WELCORP', 'EQUITASBNK', 'IOC', 'NBCC', 'JKCEMENT', 
    'SHILPAMED', 'IOLCP', 'KSB', 'GODREJAGRO', 'SARDAEN', 'HIKAL', 'SOUTHBANK', 'AEGISLOG', 'JKIL', 'IFCI', 
    'MANKIND', 'ZENSARTECH', 'HINDCOPPER', 'SKFINDIA', 'NHPC', 'TRIDENT', 'GMRAIRPORT', 'ESAFSFB', 'REDTAPE', 'VESUVIUS', 
    'TATAPOWER', 'PRSMJOHNSN', 'TVSHLTD', 'GRAPHITE', 'NEOGEN', 'JUNIPER', 'SAFARI', 'CCL', 'TIMETECHNO', 'WAAREEENER', 
    'CAMLINFINE', 'OBEROIRLTY', 'INDUSTOWER', 'EICHERMOT', 'HEROMOTOCO', 'RITES', 'GATEWAY', 'IONEXCHANG', 'ZEEL', 'PIIND', 
    'ABSLAMC', 'CIEINDIA', 'SANGHIIND', 'MCX', 'PGEL', 'DEVYANI', 'HCC', 'METROBRAND', 'VARROC', 'JISLJALEQS', 
    'CAMS', 'BALMLAWRIE', 'UJJIVANSFB', 'ICIL', 'TEXRAIL', 'GLOBUSSPR', 'MANINFRA', 'AARTIIND', 'KIMS', 'STLTECH', 
    'NCC', 'BALKRISIND', 'GHCL', 'TIRUMALCHM', 'GRINFRA', 'AETHER', 'PDSL', 'SJVN', 'UNOMINDA', 'IFBIND', 
    'HATHWAY', 'FINEORG', 'HEG', 'NTPC', 'SAGCEM', 'RTNPOWER', 'PATANJALI', 'GPIL', 'BECTORFOOD', 'LICI', 
    'ONGC', 'YESBANK', 'SUNPHARMA', 'KFINTECH', 'LEMONTREE', 'MRF', 'LUPIN', 'JCHAC', 'TATACHEM', 'DEEPAKFERT', 
    'RRKABEL', 'ACE', 'INFIBEAM', 'SCI', 'MFSL', 'MARKSANS', 'JINDWORLD', 'UTKARSHBNK', 'MASFIN', 'GAIL', 
    'SOLARINDS', 'NAVA', 'NIVABUPA', 'CARERATING', 'RHIM', 'INGERRAND', 'COALINDIA', 'AKUMS', 'FSL', 'FINPIPE', 
    'DMART', 'POWERMECH', 'BHARATFORG', 'INDIANB', 'AMBER', 'GLAND', 'TRIVENI', 'IRFC', 'MARUTI', 'GSFC', 
    'HEMIPROP', 'MIDHANI', 'IEX', 'CHOLAFIN', 'MEDPLUS', 'PFC', 'ASHOKA', 'PTC', 'MGL', 'AXISBANK', 
    'RVNL', 'AMBUJACEM', 'SIEMENS', 'POLYPLEX', 'DALMIASUG', 'NTPCGREEN', 'BHARTIHEXA', 'PHOENIXLTD', 'KPIL', 'BIOCON', 
    'PURVA', 'BASF', 'ERIS', 'AHLUCONT', 'STARHEALTH', 'TECHM', 'IDEAFORGE', 'JLHL', 'RATEGAIN', 'VBL', 
    'LGBBROSLTD', 'WHIRLPOOL', 'JSWHL', 'APLLTD', 'VRLLOG', 'RCF', 'ORISSAMINE', 'KSCL', 'IRCTC', 'MAHSEAMLES', 
    'JSWSTEEL', 'JAMNAAUTO', 'VOLTAMP', 'BLUESTARCO', 'UFLEX', 'GREENPLY', 'ALKYLAMINE', 'ASIANPAINT', 'EMCURE', 'ACI', 
    'CHEMPLASTS', 'HDFCAMC', 'AADHARHFC', 'JKTYRE', 'INDGN', 'LAOPALA', 'BANDHANBNK', 'MAHABANK', 'KPIGREEN', 'MOTHERSON', 
    'CRAFTSMAN', 'SCHAEFFLER', 'INDOCO', 'UNITDSPR', 'MARICO', 'TATACOMM', 'ARVINDFASN', 'GRANULES', 'FIRSTCRY', 'SENCO', 
    'ANGELONE', 'GODREJCP', 'NUVAMA', 'BEML', 'RECLTD', 'ABB', 'CAMPUS', 'SANOFI', 'MAZDOCK', 'KIRLPNU', 
    'SRF', 'NATCOPHARM', 'AGI', 'JUBLFOOD', 'CYIENTDLM', 'VEDL', 'RBA', 'JAIBALAJI', 'GRASIM', 'INFY', 
    'NOCIL', 'SINDHUTRAD', 'GOPAL', 'MSUMI', 'RTNINDIA', 'ALOKINDS', 'NFL', 'PREMIERENE', 'EMUDHRA', 'WONDERLA', 
    'LICHSGFIN', 'TMB', 'RBLBANK', 'BEPL', 'OLAELEC', 'DRREDDY', 'DCBBANK', 'BAJAJFINSV', 'GICRE', 'HNDFDS', 
    'JIOFIN', 'SAGILITY', 'JKLAKSHMI', 'MSTCLTD', 'AUBANK', 'UNIPARTS', 'TIPSMUSIC', 'AJANTPHARM', 'CIPLA', 'CANFINHOME', 
    'ADVENZYMES', 'JINDALSTEL', 'ELECON', 'DABUR', 'INDIACEM', 'BOMDYEING', 'INDIGOPNTS', 'TRITURBINE', 'TTML', 'VENKEYS', 
    'TATAELXSI', 'PIDILITIND', 'UBL', 'BAJAJHFL', 'OPTIEMUS', 'SUNDARMFIN', 'IGL', 'MAPMYINDIA', 'HAVELLS', 'TATACONSUM', 
    'WELENT', 'NUVOCO', 'ITC', 'GSPL', 'MPHASIS', 'EASEMYTRIP', 'BOSCHLTD', 'TCS', 'VMART', 'BEL', 
    'HINDWAREAP', 'LXCHEM', 'GAEL', 'FIVESTAR', 'FEDERALBNK', 'NMDC', 'SHREECEM', 'LTIM', 'LTF', 'BAJAJHIND', 
    'TIMKEN', 'IDFCFIRSTB', 'LT', 'SAREGAMA', 'ISGEC', 'HDFCLIFE', 'TATASTEEL', 'CHENNPETRO', 'TEGA', 'APLAPOLLO', 
    'SUNFLAG', 'HINDOILEXP', 'COCHINSHIP', 'NEWGEN', 'COHANCE', 'DHANUKA', 'POONAWALLA', 'NIFTY', 'LLOYDSME', 'MOIL', 
    'ETERNAL', 'IRCON', 'SUNTV', 'CDSL', 'HINDZINC', 'KTKBANK', 'FEDFINA', 'SBFC', 'BAJFINANCE', 'ICICIPRULI', 
    'WIPRO', 'ENGINERSIN', 'SPARC', 'JAICORPLTD', 'VOLTAS', 'CASTROLIND', 'PETRONET', 'ASTRAL', 'BANKNIFTY', 'TEAMLEASE', 
    'TVSMOTOR', 'NAM-INDIA', 'CUMMINSIND', 'GESHIP', 'NETWORK18', 'BRITANNIA', 'DEEPAKNTR', 'GMMPFAUDLR', 'GLAXO', 'HAPPYFORGE', 
    'SUNDRMFAST', 'TATAMOTORS', 'FIEMIND', 'RELIANCE', 'CYIENT', 'STAR', 'BOROLTD', 'SULA', 'KANSAINER', 'APOLLOHOSP', 
    'BLUEJET', 'JKPAPER', 'HERITGFOOD', 'CONFIPET', 'SUNTECK', 'HSCL', 'ABCAPITAL', 'VSTTILLERS', 'ROLEXRINGS', 'GNFC', 
    'CSBBANK', 'SPANDANA', 'PRESTIGE', 'NAUKRI', 'ORIENTELEC', 'ELECTCAST', 'INDIGO', 'RELIGARE', 'BATAINDIA', 'CGPOWER', 
    'PRAJIND', 'SHAREINDIA', 'THERMAX', 'RAYMOND', 'CMSINFO', 'RAIN', 'IMAGICAA', 'DEN', 'DLF', 'ASKAUTOLTD', 
    'LUXIND', 'BERGEPAINT', 'KALYANKJIL', 'BSE', 'TEJASNET', 'LLOYDSENGG', 'JTEKTINDIA', 'UTIAMC', 'IIFLCAPS', 'JYOTHYLAB', 
    'CRISIL', 'ANANDRATHI', 'MUTHOOTFIN', 'HOMEFIRST', 'RAMCOCEM', 'SHYAMMETL', 'GODIGIT', 'LATENTVIEW', 'GRSE', 'CHAMBLFERT', 
    'APOLLOTYRE', 'GUJGASLTD', 'KARURVYSYA', 'JPPOWER', 'ANURAS', 'FCL', 'INDHOTEL', 'DIXON', 'NH', 'VSTIND', 
    'AUROPHARMA', 'HMAAGRO', 'ABREL', 'ACUTAAS', 'KEC', 'HINDALCO', 'BAJAJCON', 'SCHNEIDER', 'CROMPTON', 'ULTRACEMCO', 
    'STYLAMIND', 'BBTC', 'NYKAA', 'KIRLOSBROS', 'ZYDUSWELL', 'RAILTEL', 'TECHNOE', 'DBCORP', 'MRPL', 'LMW', 
    'MEDANTA', 'SONACOMS', 'POWERGRID', 'DODLA', 'ZYDUSLIFE', 'HONAUT', 'HDFCBANK', 'AWL', 'DHANI', 'BLS', 
    'NATIONALUM', 'TVSSCS', 'ICICIGI', 'WSTCSTPAPR', 'KAYNES', 'HINDUNILVR', 'ZENTEC', 'MHRIL', 'PVRINOX', 'PRICOLLTD', 
    'APARINDS', 'LTTS', 'EPIGRAL', 'GANESHHOU', 'GRAVITA', 'ELGIEQUIP', 'PERSISTENT', 'GLENMARK', 'PARKHOTELS', 'ENDURANCE', 
    'ARE&M', 'UPL', 'SAMHI', 'IRB', 'BAJAJ-AUTO', 'SHRIPISTON', 'KOTAKBANK', 'TCIEXP', 'SBCL', 'PRINCEPIPE', 
    'AIIL', 'COLPAL', 'KAJARIACER', 'MAXHEALTH', 'DELHIVERY', 'RALLIS', 'RAJESHEXPO', 'NESTLEIND', 'HONASA', 'PNCINFRA', 
    'TRENT', 'KPITTECH', 'NUCLEUS', 'TITAN', 'BALRAMCHIN', 'BAJAJELEC', 'CEATLTD', 'CHOICEIN', 'EVEREADY', 'CONCOR', 
    'MAHLIFE', 'CERA', 'JUBLPHARMA', 'DBL', 'MANYAVAR', 'EPL', 'WOCKPHARMA', 'TARSONS', 'ICICIBANK', 'M&M', 
    'JBMA', 'TTKPRESTIG', 'JUSTDIAL', 'CLEAN', 'MAITHANALL', 'SUPREMEIND', 'HCG', 'JSFB', 'JWL', 'OLECTRA', 
    'AVALON', 'FORTIS', 'SAPPHIRE', '3MINDIA', 'GPPL', 'INDIASHLTR', 'ASTRAZEN', 'IMFA', 'HGINFRA', 'ZFCVINDIA', 
    'DALBHARAT', 'TORNTPOWER', 'PAGEIND', 'GULFOILLUB', 'GREAVESCOT', 'HFCL', 'FINCABLES', 'COFORGE', 'SONATSOFTW', 'ENTERO', 
    'RESPONIND', 'YATHARTH', 'MUTHOOTMF', 'PFIZER', 'KRSNAA', 'IPL', 'KNRCON', 'BRIGADE', 'BLUEDART', 'ABBOTINDIA', 
    'OFSS', 'SUBROS', 'KRBL', 'PSPPROJECT', 'JTLIND', 'BSOFT', 'HCLTECH', 'TIINDIA', 'MASTEK', 'RKFORGE', 
    'CREDITACC', 'POWERINDIA', 'IGIL', 'FORCEMOT', 'INOXINDIA', 'COROMANDEL', 'QUESS', 'WELSPUNLIV', 'TI', '360ONE', 
    'BAJAJHLDNG', 'FLAIR', 'AIAENG', 'MANAPPURAM', 'CIGNITITEC', 'CELLO', 'LINDEINDIA', 'NAVINFLUOR', 'SSWL', 'SFL', 
    'RAINBOW', 'SOBHA', 'INDIAMART', 'BALAMINES', 'NAZARA', 'KALAMANDIR', 'NIITMTS', 'WESTLIFE', 'VTL', 'TATAINVEST', 
    'SBICARD', 'ROUTE', 'HBLENGINE', 'GRINDWELL', 'CHALET', 'ARVIND', 'EXIDEIND', 'BARBEQUE', 'EIDPARRY', 'NEULANDLAB', 
    'JMFINANCIL', 'DISHTV', 'EIHOTEL', 'RATNAMANI', 'ESCORTS', 'VAIBHAVGBL', 'CARBORUNIV', 'ACMESOLAR', 'ALLCARGO', 'ATUL', 
    'ECLERX', 'ORIENTCEM', 'SIGNATURE', 'RAYMONDLSL', 'GUJALKALI', 'LANDMARK', 'POLYMED', 'GODREJIND', 'RELINFRA', 'PTCIL', 
    'EMAMILTD', 'EMBDL', 'SANGHVIMOV', 'ASAHIINDIA', 'PAYTM', 'DCMSHRIRAM', 'PEL', 'JUBLINGREA', 'DREAMFOLKS', 'PAISALO', 
    'CEMPRO'
  ],
  
  MULTICAPPLUS: [
    // Add MULTICAPPLUS stocks here when provided
    // This will be populated with actual MULTICAPPLUS stocks
  ],
  
  FNO: [
    'IDEA', 'ADANIGREEN', 'ADANIENT', 'ADANIENSOL', 'IREDA', 'SAMMAANCAP', 'GODREJPROP', 'UNIONBANK', 'HUDCO', 'PPLPHARMA', 
    'SAIL', 'SUZLON', 'CANBK', 'INOXWIND', 'TORNTPHARM', 'ASHOKLEY', 'POLYCAB', 'DIVISLAB', 'JSWENERGY', 'BDL', 
    'PNB', 'BANKBARODA', 'OIL', 'BANKINDIA', 'HAL', 'KEI', 'INDUSINDBK', 'BPCL', 'SYNGENE', 'BHEL', 
    'ALKEM', 'POLICYBZR', 'BHARTIARTL', 'SBILIFE', 'HINDPETRO', 'ADANIPORTS', 'IIFL', 'SHRIRAMFIN', 'TATATECH', 'LAURUSLABS', 
    'LODHA', 'PNBHOUSING', 'TITAGARH', 'SBIN', 'IOC', 'NBCC', 'MANKIND', 'NHPC', 'GMRAIRPORT', 'TATAPOWER', 
    'OBEROIRLTY', 'INDUSTOWER', 'EICHERMOT', 'HEROMOTOCO', 'PIIND', 'MCX', 'PGEL', 'CAMS', 'NCC', 'UNOMINDA', 
    'NTPC', 'PATANJALI', 'LICI', 'ONGC', 'YESBANK', 'SUNPHARMA', 'KFINTECH', 'LUPIN', 'TATACHEM', 'MFSL', 
    'GAIL', 'SOLARINDS', 'COALINDIA', 'DMART', 'BHARATFORG', 'INDIANB', 'AMBER', 'IRFC', 'MARUTI', 'IEX', 
    'CHOLAFIN', 'PFC', 'AXISBANK', 'RVNL', 'AMBUJACEM', 'SIEMENS', 'PHOENIXLTD', 'BIOCON', 'TECHM', 'VBL', 
    'IRCTC', 'JSWSTEEL', 'BLUESTARCO', 'ASIANPAINT', 'HDFCAMC', 'BANDHANBNK', 'MOTHERSON', 'UNITDSPR', 'MARICO', 'CNXMIDCAP', 
    'ANGELONE', 'GODREJCP', 'NUVAMA', 'RECLTD', 'ABB', 'MAZDOCK', 'SRF', 'JUBLFOOD', 'VEDL', 'GRASIM', 
    'INFY', 'LICHSGFIN', 'RBLBANK', 'DRREDDY', 'BAJAJFINSV', 'JIOFIN', 'AUBANK', 'CIPLA', 'JINDALSTEL', 'DABUR', 
    'TATAELXSI', 'PIDILITIND', 'IGL', 'HAVELLS', 'TATACONSUM', 'ITC', 'MPHASIS', 'BOSCHLTD', 'TCS', 'BEL', 
    'FEDERALBNK', 'NMDC', 'SHREECEM', 'LTIM', 'LTF', 'IDFCFIRSTB', 'LT', 'HDFCLIFE', 'TATASTEEL', 'APLAPOLLO', 
    'NIFTY', 'ETERNAL', 'CDSL', 'HINDZINC', 'BAJFINANCE', 'ICICIPRULI', 'WIPRO', 'VOLTAS', 'PETRONET', 'ASTRAL', 
    'BANKNIFTY', 'TVSMOTOR', 'CUMMINSIND', 'BRITANNIA', 'TATAMOTORS', 'RELIANCE', 'CYIENT', 'APOLLOHOSP', 'ABCAPITAL', 'PRESTIGE', 
    'NAUKRI', 'INDIGO', 'CGPOWER', 'DLF', 'KALYANKJIL', 'BSE', 'MUTHOOTFIN', 'INDHOTEL', 'DIXON', 'AUROPHARMA', 
    'HINDALCO', 'CROMPTON', 'ULTRACEMCO', 'NYKAA', 'SONACOMS', 'POWERGRID', 'ZYDUSLIFE', 'HDFCBANK', 'NATIONALUM', 'ICICIGI', 
    'KAYNES', 'HINDUNILVR', 'PERSISTENT', 'GLENMARK', 'UPL', 'BAJAJ-AUTO', 'KOTAKBANK', 'COLPAL', 'MAXHEALTH', 'DELHIVERY', 
    'NESTLEIND', 'TRENT', 'KPITTECH', 'TITAN', 'CONCOR', 'ICICIBANK', 'M&M', 'SUPREMEIND', 'FORTIS', 'DALBHARAT', 
    'TORNTPOWER', 'PAGEIND', 'HFCL', 'COFORGE', 'OFSS', 'HCLTECH', 'TIINDIA', '360ONE', 'MANAPPURAM', 'SBICARD', 
    'EXIDEIND', 'PAYTM'
  ],
  
  CUSTOM: [
    // This will be managed dynamically by the user
  ]
};

// Helper function to get stocks for a basket
export const getStocksForBasket = (basketName) => {
  return STOCK_BASKETS[basketName] || [];
};

// Helper function to check if a stock belongs to a basket
export const isStockInBasket = (stockSymbol, basketName) => {
  if (basketName === 'ALL') return true;
  const basketStocks = getStocksForBasket(basketName);
  return basketStocks.includes(stockSymbol);
};

// Helper function to get the count of stocks in a basket
export const getBasketCount = (basketName) => {
  if (basketName === 'ALL') return 'All';
  const basketStocks = getStocksForBasket(basketName);
  return basketStocks.length;
};
